defaults:
  - _self_
  - algorithm: sac
  - env: half_cheetah  # this includes values for environment specific overrides
  - logger: wandb

root_dir: "../experiments"
device: "cpu"
run_id: 0

hydra:
  run:
    dir: ${root_dir}/${algorithm.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${root_dir}/${algorithm.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

