defaults:
  - _self_
  - env: half_cheetah
  - agent: sac
  - ctrl: pd
  - mp: idmp
  - train: off_policy
  - buffer: random_replay_buffer

root_dir: "../experiments"
mode: "train_sac"
device: "cpu"
run: 0

hydra:
  run:
    dir: ${root_dir}/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${root_dir}/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}

