defaults:
  - _self_
  - env: half_cheetah
  - agent: mp_time_sac
  - ctrl: pd
  - mp: idmp
  - train: off_policy
  - buffer: sequence_buffer

root_dir: "../experiments"
mode: "train_stepwise_mp_sac"
device: "cpu"

hydra:
  run:
    dir: ${root_dir}/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${root_dir}/${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}

