name: "mixture_of_experts"

network_width: 256
num_experts: 4
variance: 0.25
use_batch_normalization: False
naive_state_input: False  # use inherent state information for prediction

state_dim_in: ${env.moe.state_dim_in}
state_dim_out: ${env.moe.state_dim_out}
action_dim: ${env.moe.action_dim}
