name: "HalfCheetah"

num_dof: 6
q_dim: 8
vel_dim: 8
time_out: 1000  # only for SAC activated

action_dim: 6
state_dim: 17
coordinate_dim: 1
dt: 0.05

pd:
  pgains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  dgains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

idmp:
  num_basis: 5
  basis_bandwidth_factor: 1.0
