name: "Humanoid"

num_dof: 8
time_out: 1000  # only for SAC activated

action_dim: 17
state_dim: 376
sim_qpos_dim: 24
sim_qvel_dim: 23
coordinate_dim: 2
dt: 0.015

pd:
  pgains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  dgains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

idmp:
  num_basis: 10
  basis_bandwidth_factor: 1.0

sac:
  alpha: 0.05
  hidden_size: 512
