name: "MetaReacher"

num_dof: 2
q_dim: 2
vel_dim: 2
time_out: 1000  # only for SAC activated

action_dim: 4
state_dim: 39
coordinate_dim: 0
dt: 0.02

pd:
  pgains: [1.0, 1.0]
  dgains: [0.1, 0.1]

idmp:
  num_basis: 5
  basis_bandwidth_factor: 1.0

sac:
  alpha: 0.2
  hidden_size: 512
