mp_type: "prodmp"

num_basis: ${env.idmp.num_basis}
num_dof: ${env.action_dim}
device: ${device}

mp_args:
  alpha_phase: 1.0
  num_basis: ${env.idmp.num_basis}
  basis_bandwidth_factor: ${env.idmp.basis_bandwidth_factor}
  num_basis_outside: 0
  dt: ${env.dt}
  alpha: 20
  weight_scale: 2.0
  goals_scale: 0.0