defaults:
  - _self_
  - alg: sac
  - buffer: settings
  - env: half_cheetah
  - eval: scheme
  - logging: wandb
  - prediction: off_policy
  - train: scheme

root_dir: "../experiments"
device: "cpu"
project_name: "sac-trl-model"
run_id: 0

hydra:
  run:
    dir: ${root_dir}/${alg.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${root_dir}/${alg.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

