defaults:
  - _self_
  - alg: sac_mixed_mp
  - buffer: settings
  - env: half_cheetah
  - eval: scheme
  - logging: wandb
  - prediction: off_policy
  - train: scheme

root_dir: "./experiment"
project_name: "mprl"
run_id: 0

hydra:
  run:
    dir: ${root_dir}/${alg.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${root_dir}/${alg.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

