name: "mp_t_sac"
gamma: 0.99
tau: 0.005
alpha: 0.2
lr: 0.0003
learn_time: False
time_steps: 2  # will be used if learn time is False
full_std: False
automatic_entropy_tuning: False
device: ${device}
hidden_size: 256
num_basis: ${env.idmp.num_basis}
num_dof: ${env.num_dof}

env:
  action_dim: ${env.action_dim}
  state_dim: ${env.state_dim}

