name: "ssac"
gamma: 0.99
tau: 0.995
alpha: 0.2
automatic_entropy_tuning: True
device: {$device}
hidden_size: 512

env:
  action_dim: (${env.promp.num_basis} * (${env.promp.num_basis} + 1)) / 2 + ${env.promp.num_basis}  # This includes mean and L of MP
  state_dim: ${env.state_dim}

