defaults:
  - ctrl: none
  - mp: none
  - network: ff
  - tr: none

name: "sac"

alpha: ${env.sac.alpha}
auto_alpha: ${env.sac.auto_alpha}
target_entropy: ${env.sac.target_entropy}
gamma: 0.99
tau_target: 0.005
warm_start_steps: 10000
