defaults:
  - ctrl: pd
  - network: ff
  - mp: idmp
  - tr: settings

name: "sac_tr"

alpha: ${env.sac_tr.alpha}
alpha_q: ${env.sac_tr.alpha_q}
auto_alpha: ${env.sac_tr.auto_alpha}
use_imp_sampling: False
num_steps: ${env.idmp.num_steps}
target_entropy: ${env.sac_tr.target_entropy}
layer_type: ${env.sac_tr.layer_type}
gamma: 0.99
policy_loss: "mean"  # other is mean
q_loss: "off_policy"  # other is on_policy
learn_bc: False
target_tau: 0.005
warm_start_steps: 0
