defaults:
  - ctrl: pd
  - hyper: sac_mp
  - mp: idmp
  - network: ff
  - tr: none

name: "sac_mp"

alpha: ${env.sac_mp.alpha}
alpha_q: ${env.sac_mp.alpha_q}
auto_alpha: ${env.sac_mp.auto_alpha}
gamma: 0.99
target_tau: 0.005
warm_start_steps: 0
