alpha: ${env.sac.alpha}
alpha_q: ${env.sac_mixed_mp.alpha_q}
auto_alpha: ${env.sac.auto_alpha}
target_entropy: ${env.sac.target_entropy}
basis_bandwidth_factor: ${env.idmp.basis_bandwidth_factor}
gamma: 0.99
num_basis: ${env.idmp.num_basis}
num_dof: ${env.num_dof}
tau: 0.005
warm_start_steps: 10000
num_steps: 1
