alpha: ${env.sac_tr.alpha}
alpha_q: ${env.sac_tr.alpha_q}
auto_alpha: ${env.sac_tr.auto_alpha}
mean_bound: ${env.sac_tr.mean_bound}
cov_bound: ${env.sac_tr.cov_bound}
use_imp_sampling: False
target_entropy: ${env.sac_tr.target_entropy}
basis_bandwidth_factor: ${env.idmp.basis_bandwidth_factor}
gamma: 0.99
num_basis: ${env.idmp.num_basis}
num_dof: ${env.num_dof}
num_steps: ${env.sac_tr.num_steps}
policy_loss: "mean_performance"  # other is mean
tau: 0.005
warm_start_steps: 0
