alpha: 0.1
alpha_q: 0.1
basis_bandwidth_factor: ${env.idmp.basis_bandwidth_factor}
gamma: 0.99
num_basis: ${env.idmp.num_basis}
num_dof: ${env.num_dof}
num_steps: 5
policy_loss: "weighted"  # other options is "weighted"
tau: 0.005
