name: "Ant"

action_dim: 8
dt: 0.05
state_dim: 27  # exclude contact forces
time_out_after: 1000
sim_qp_dim: 15
sim_qv_dim: 14

pd:
  pgains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  dgains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

sac:
  alpha: 0.1
  auto_alpha: True
  target_entropy: -8

network:
  network_width: 256
  network_depth: 2
