name: "HalfCheetah"

num_dof: 6
q_dim: 8
vel_dim: 8
time_out_after: 1000
action_dim: 6
state_dim: 17
sim_qpos_dim: 9
sim_qvel_dim: 9
dt: 0.05

pd:
  pgains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  dgains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

idmp:
  num_basis: 5
  basis_bandwidth_factor: 1.0

sac:
  alpha: 0.1

sac_mixed_mp:
  alpha: 0.05
  alpha_q: 0.0

network:
  network_width: 256
  network_depth: 2
