name: "HalfCheetah"

num_dof: 6
q_dim: 8
vel_dim: 8
time_out_after: 1000
action_dim: 6
state_dim: 17
sim_qpos_dim: 9
sim_qvel_dim: 9
dt: 0.05

pd:
  pgains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  dgains: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

idmp:
  num_basis: 10
  basis_bandwidth_factor: 1.0

sac:
  alpha: 0.1
  auto_alpha: True
  target_entropy: -6

sac_mixed_mp:
  alpha: 0.01
  alpha_q: 0.0
  auto_alpha: False
  target_entropy: -48
  tau_idmp: 0.5
  num_steps: 10

sac_tr:
  alpha: 0.0
  alpha_q: 0.0
  auto_alpha: False
  target_entropy: -48
  tau_idmp: 0.5
  num_steps: 10
  layer_type: "kl"
  mean_bound: 0.03
  cov_bound: 0.001

sac_mp:
  alpha: 0.5

network:
  network_width: 256
  network_depth: 2
  action_scale: 1.0
