name: "HalfCheetah"

action_dim: 6
dt: 0.05
state_dim: 17
time_out_after: 1000
sim_qp_dim: 9
sim_qv_dim: 9

pd:
  pgains: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  dgains: [0.02, 0.02, 0.02, 0.02, 0.02, 0.02]

idmp:
  num_basis: 10
  basis_bandwidth_factor: 1.0
  num_steps: 10

sac:
  alpha: 0.1
  auto_alpha: True
  target_entropy: -6

sac_mp:
  alpha: 0.1

sac_mixed_mp:
  alpha: 0.01
  alpha_q: 0.01
  auto_alpha: False
  target_entropy: -48

sac_tr:
  alpha: 0.0
  alpha_q: 0.0
  auto_alpha: False
  target_entropy: -48
  layer_type: "kl"
  mean_bound: 0.01
  cov_bound: 0.0015

network:
  network_width: 256
  network_depth: 2
  action_scale: 0.8

moe:
  state_dim_in: 16
  state_dim_out: 17
