name: "Hopper"

action_dim: 3
dt: 0.008
state_dim: 11
time_out_after: 1000  # only for SAC activated
sim_qp_dim: 6
sim_qv_dim: 6

pd:
  pgains: [1.0, 1.0, 1.0]
  dgains: [0.1, 0.1, 0.1]

sac:
  alpha: 0.1
  auto_alpha: True
  target_entropy: -3

network:
  network_width: 256
  network_depth: 2
