name: "MetaReach"

action_dim: 4
dt: 0.0125
state_dim: 39
time_out_after: 500
sim_qp_dim: 16
sim_qv_dim: 15

pd:
  pgains: [10.0, 10.0, 10.0, -3.0]  # weird ctrl for gripper (see tuning in utils)

idmp:
  num_basis: 10
  basis_bandwidth_factor: 1.0
  num_steps: 50

sac:
  alpha: 0.1
  auto_alpha: True
  target_entropy: -4

sac_mixed_mp:
  alpha: 0.025
  alpha_q: 0.0
  auto_alpha: False
  target_entropy: -30

sac_tr:
  alpha: 0.0
  alpha_q: 0.0
  auto_alpha: False
  target_entropy: -100
  layer_type: "kl"
  mean_bound: 0.03
  cov_bound: 0.001

network:
  network_width: 256
  network_depth: 2
  action_scale: 0.7

moe:
  state_dim_in: 21
  state_dim_out: 21
