name: "OriginalMetaReacher"

num_dof: 4
q_dim: 9
vel_dim: 2
time_out_after: 500

action_dim: 4
state_dim: 39
sim_qpos_dim: 16
sim_qvel_dim: 15
coordinate_dim: 0
dt: 0.0125

pd:
  pgains: [1.0, 1.0, 1.0]

idmp:
  num_basis: 5
  basis_bandwidth_factor: 1.0

sac:
  alpha: 0.2

sac_mixed_mp:
  alpha: 0.05
  alpha_q: 0.0

network:
  network_width: 256
  network_depth: 2
  action_scale: 10.0
