name: "Reacher"

num_dof: 2
q_dim: 2
vel_dim: 2
time_out_after: 200

action_dim: 2
state_dim: 11
sim_qpos_dim: 4
sim_qvel_dim: 4
coordinate_dim: 0
dt: 0.02

pd:
  pgains: [1.0, 1.0]
  dgains: [0.1, 0.1]

idmp:
  num_basis: 5
  basis_bandwidth_factor: 1.0

sac:
  alpha: 0.1

sac_mixed_mp:
  alpha: 0.05
  alpha_q: 0.0

network:
  network_width: 256
  network_depth: 2
