name: "Reacher"

num_dof: 2
q_dim: 2
vel_dim: 2
time_out_after: 50

action_dim: 2
state_dim: 11
sim_qpos_dim: 4
sim_qvel_dim: 4
coordinate_dim: 0
dt: 0.02

pd:
  pgains: [1.0, 1.0]
  dgains: [0.1, 0.1]

idmp:
  num_basis: 7
  basis_bandwidth_factor: 1.0

sac:
  alpha: 0.2
  auto_alpha: True
  target_entropy: -2

sac_mixed_mp:
  alpha: 0.0
  alpha_q: 0.0
  auto_alpha: True
  target_entropy: -100
  tau_idmp: 0.4
  num_steps: 20

network:
  network_width: 128
  network_depth: 2
  action_scale: 1.0
