name: "Reacher"

action_dim: 2
dt: 0.02
state_dim: 11
time_out_after: 50
sim_qp_dim: 4
sim_qv_dim: 4

pd:
  pgains: [0.5, 0.5]  # usually underactuated gains perform better
  dgains: [0.01, 0.01]

idmp:
  num_basis: 10
  basis_bandwidth_factor: 1.0
  num_steps: 20

sac:
  alpha: 0.2
  auto_alpha: True
  target_entropy: -2

sac_mixed_mp:
  alpha: 0.005
  alpha_q: 0.005
  auto_alpha: False
  target_entropy: -48

sac_tr:
  alpha: 0.025
  alpha_q: 0.0
  auto_alpha: False
  target_entropy: -48
  layer_type: "kl"
  mean_bound: 0.03
  cov_bound: 0.003

sac_mp:
  alpha: 0.5


network:
  network_width: 128
  network_depth: 2
  action_scale: 1.0

moe:
  state_dim_in: 11
  state_dim_out: 11
