name: "Reacher"


action_dim: 2
dt: 0.02
state_dim: 11
time_out_after: 50

pd:
  pgains: [1.0, 1.0]
  dgains: [0.1, 0.1]

idmp:
  num_basis: 10
  basis_bandwidth_factor: 1.0
  num_steps: 20

sac:
  alpha: 0.2
  auto_alpha: True
  target_entropy: -2

sac_mixed_mp:
  alpha: 0.025
  alpha_q: 0.0
  auto_alpha: False
  target_entropy: -48

sac_tr:
  alpha: 0.025
  alpha_q: 0.0
  auto_alpha: False
  target_entropy: -48
  layer_type: "kl"
  mean_bound: 0.03
  cov_bound: 0.003

sac_mp:
  alpha: 0.5


network:
  network_width: 128
  network_depth: 2

moe:
  state_dim_in: 11
  state_dim_out: 11
