name: "idmp"

alpha: 25
tau: 1.0
num_basis: ${env.idmp.num_basis}
num_dof: ${env.num_dof}

mp_args:
  alpha_phase: 25.0
  num_basis: ${env.idmp.num_basis}
  basis_bandwidth_factor: ${env.idmp.basis_bandwidth_factor}
  num_basis_outside: 0
  dt: ${env.dt}
  alpha: 25