name: "mp_sac"
gamma: 0.99
tau: 0.005
alpha: 0.1
lr: 0.0003
learn_time: True
time_steps: 5
automatic_entropy_tuning: False
device: ${device}
hidden_size: 512
num_basis: ${env.idmp.num_basis}
num_dof: ${env.num_dof}

env:
  action_dim: ${env.action_dim}
  state_dim: ${env.state_dim}

