name: "sac"
gamma: 0.99
tau: 0.005
alpha: ${env.sac.alpha}
lr: 0.0003
automatic_entropy_tuning: False
device: ${device}
hidden_size: ${env.sac.hidden_size}

env:
  action_dim: ${env.action_dim}
  state_dim: ${env.state_dim}

