[run.one]
project_name="mprl-sac-mp-toml"
algorithm="sac_mixed_mp"
env="half_cheetah"

cluster_hours=15
jobs=3

    [run.one.alg]
    policy_loss="mean_performance"

    [run.one.buffer]
    capacity=1000000
