[run.smm1]
project_name="f-sac-tr-hc"
algorithm="sac_tr"
env="half_cheetah"
cluster_hours=72
jobs=2

[run.smm1.buffer]
capacity=100000
capacity_policy=100000

[run.smm1.alg]
alpha=0.0
alpha_q=0.0
mean_bound=0.01
cov_bound=0.001

# ----------------------------

[run.smm2]
project_name="f-sac-tr-hc"
algorithm="sac_tr"
env="half_cheetah"
cluster_hours=72
jobs=2

[run.smm2.buffer]
capacity=100000
capacity_policy=100000

[run.smm2.alg]
alpha=0.0
alpha_q=0.0
mean_bound=0.01
cov_bound=0.0005

# ----------------------------

[run.smm3]
project_name="f-sac-tr-hc"
algorithm="sac_tr"
env="half_cheetah"
cluster_hours=72
jobs=2

[run.smm3.buffer]
capacity=100000
capacity_policy=100000

[run.smm3.alg]
alpha=0.0
alpha_q=0.0
mean_bound=0.01
cov_bound=0.0001

# ----------------------------

[run.smm4]
project_name="f-sac-tr-hc"
algorithm="sac_tr"
env="half_cheetah"
cluster_hours=72
jobs=2

[run.smm4.buffer]
capacity=100000
capacity_policy=100000

[run.smm4.alg]
alpha=0.0
alpha_q=0.0
mean_bound=0.005
cov_bound=0.001

# ----------------------------

[run.smm5]
project_name="f-sac-tr-hc"
algorithm="sac_tr"
env="half_cheetah"
cluster_hours=72
jobs=2

[run.smm5.buffer]
capacity=100000
capacity_policy=100000

[run.smm5.alg]
alpha=0.0
alpha_q=0.0
mean_bound=0.005
cov_bound=0.0005

# ----------------------------

[run.smm6]
project_name="f-sac-tr-hc"
algorithm="sac_tr"
env="half_cheetah"
cluster_hours=72
jobs=2

[run.smm6.buffer]
capacity=100000
capacity_policy=100000

[run.smm6.alg]
alpha=0.0
alpha_q=0.0
mean_bound=0.005
cov_bound=0.0001
