[run.smm1]
project_name="f-smm-meta"
algorithm="sac_mixed_mp"
env="meta_reach"
cluster_hours=72
jobs=3

[run.smm1.buffer]
capacity=1000000
capacity_policy=200

[run.smm1.alg]
q_loss="off_policy"
alpha=0.01
alpha_q=0.01

# ------------------------------

[run.smm2]
project_name="f-smm-meta"
algorithm="sac_mixed_mp"
env="meta_reach"
cluster_hours=72
jobs=3

[run.smm2.buffer]
capacity=1000000
capacity_policy=200

[run.smm2.alg]
q_loss="off_policy"
alpha=0.05
alpha_q=0.05

# ------------------------------

[run.smm3]
project_name="f-smm-meta"
algorithm="sac_mixed_mp"
env="meta_reach"
cluster_hours=72
jobs=3

[run.smm3.buffer]
capacity=1000000
capacity_policy=200

[run.smm3.alg]
q_loss="off_policy"
alpha=0.005
alpha_q=0.005

# ------------------------------
[run.smm4]
project_name="f-smm-meta"
algorithm="sac_mixed_mp"
env="meta_push"
cluster_hours=72
jobs=3

[run.smm4.buffer]
capacity=1000000
capacity_policy=200

[run.smm4.alg]
q_loss="off_policy"
alpha=0.01
alpha_q=0.01

# ------------------------------

[run.smm5]
project_name="f-smm-meta"
algorithm="sac_mixed_mp"
env="meta_push"
cluster_hours=72
jobs=3

[run.smm5.buffer]
capacity=1000000
capacity_policy=200

[run.smm5.alg]
q_loss="off_policy"
alpha=0.05
alpha_q=0.05

# ------------------------------

[run.smm6]
project_name="f-smm-meta"
algorithm="sac_mixed_mp"
env="meta_push"
cluster_hours=72
jobs=3

[run.smm6.buffer]
capacity=1000000
capacity_policy=200

[run.smm6.alg]
q_loss="off_policy"
alpha=0.005
alpha_q=0.005

# ------------------------------
[run.smm7]
project_name="f-smm-meta"
algorithm="sac_mixed_mp"
env="meta_button_press"
cluster_hours=72
jobs=3

[run.smm7.buffer]
capacity=1000000
capacity_policy=200

[run.smm7.alg]
q_loss="off_policy"
alpha=0.01
alpha_q=0.01

# ------------------------------

[run.smm8]
project_name="f-smm-meta"
algorithm="sac_mixed_mp"
env="meta_button_press"
cluster_hours=72
jobs=3

[run.smm8.buffer]
capacity=1000000
capacity_policy=200

[run.smm8.alg]
q_loss="off_policy"
alpha=0.05
alpha_q=0.05

# ------------------------------

[run.smm9]
project_name="f-smm-meta"
algorithm="sac_mixed_mp"
env="meta_button_press"
cluster_hours=72
jobs=3

[run.smm9.buffer]
capacity=1000000
capacity_policy=200

[run.smm9.alg]
q_loss="off_policy"
alpha=0.005
alpha_q=0.005

