[run.smm1]
project_name="f-smm-meta-v7"
algorithm="sac_tr"
env="meta_window_open"
cluster_hours=72
jobs=3

[run.smm1.buffer]
capacity=100000
capacity_policy=100000

[run.smm1.alg]
q_loss="off_policy"
learn_bc="True"
alpha=0.0
alpha_q=0.0
mean_bound=0.005
cov_bound=0.0005

# ------------------------------

[run.smm3]
project_name="f-smm-meta-v7"
algorithm="sac_tr"
env="meta_button_press"
cluster_hours=72
jobs=3

[run.smm3.buffer]
capacity=100000
capacity_policy=100000

[run.smm3.alg]
q_loss="off_policy"
learn_bc="True"
alpha=0.0
alpha_q=0.0
mean_bound=0.005
cov_bound=0.0005

# ------------------------------

[run.smm5]
project_name="f-smm-meta-v7"
algorithm="sac_tr"
env="meta_push"
cluster_hours=72
jobs=3

[run.smm5.buffer]
capacity=100000
capacity_policy=100000

[run.smm5.alg]
q_loss="off_policy"
learn_bc="True"
alpha=0.0
alpha_q=0.0
mean_bound=0.005
cov_bound=0.0005

# ------------------------------

[run.smm7]
project_name="f-smm-meta-v7"
algorithm="sac_tr"
env="meta_reach"
cluster_hours=72
jobs=3

[run.smm7.buffer]
capacity=100000
capacity_policy=100000

[run.smm7.alg]
q_loss="off_policy"
learn_bc="True"
alpha=0.0
alpha_q=0.0
mean_bound=0.005
cov_bound=0.0005

# ------------------------------
