[run.smm1]
project_name="f-smm-meta-v5"
algorithm="sac_mixed_mp"
env="half_cheetah"
cluster_hours=72
jobs=3

[run.smm1.buffer]
capacity=100000
capacity_policy=10000

[run.smm1.alg]
q_loss="off_policy"
learn_bc="True"
alpha=0.01
alpha_q=0.01

# ------------------------------

[run.smm2]
project_name="f-smm-meta-v5"
algorithm="sac_mixed_mp"
env="half_cheetah"
cluster_hours=72
jobs=3

[run.smm2.buffer]
capacity=100000
capacity_policy=10000

[run.smm2.alg]
q_loss="off_policy"
alpha=0.01
alpha_q=0.01

