[run.smm1]
project_name="f-smm-meta-v3"
algorithm="sac_mixed_mp"
env="meta_reach"
cluster_hours=72
jobs=3

[run.smm1.buffer]
capacity=100000
capacity_policy=200

[run.smm1.alg]
q_loss="off_policy"
learn_bc="True"
alpha=0.01
alpha_q=0.01

# ------------------------------

[run.smm2]
project_name="f-smm-meta-v3"
algorithm="sac_mixed_mp"
env="meta_reach"
cluster_hours=72
jobs=3

[run.smm2.buffer]
capacity=100000
capacity_policy=200

[run.smm2.alg]
q_loss="off_policy"
alpha=0.01
alpha_q=0.01

# ------------------------------

[run.smm3]
project_name="f-smm-meta-v3"
algorithm="sac_mixed_mp"
env="meta_reach"
cluster_hours=72
jobs=3

[run.smm3.buffer]
capacity=100000
capacity_policy=200

[run.smm3.alg]
q_loss="off_policy"
learn_bc="True"
alpha=0.005
alpha_q=0.005

# ------------------------------

[run.smm4]
project_name="f-smm-gt"
algorithm="sac_mixed_mp"
env="half_cheetah"
prediction="ground_truth"
cluster_hours=72
jobs=5

[run.smm4.buffer]
capacity=100000
capacity_policy=200

[run.smm4.train]
batch_size=64

[run.smm4.alg]
q_loss="off_policy"
q_model_bc="True"
alpha=0.005
alpha_q=0.005
