defaults:
  - agent: mp_sac
  - train: off_policy
  - buffer: random_replay_buffer
  - mp: idmp
  - ctrl: pd
  - prediction: moe

name: "sac_mp_stepwise"
mode: "train"
reward_weighting: "mean"  # other options is "likelihood"
