defaults:
  - agent: mp_sac
  - train: off_policy
  - buffer: random_replay_buffer
  - mp: idmp
  - ctrl: pd

name: "sac_mp_stepwise"
mode: "train"
prediction: "off_policy"  # other options are "ground_truth" and "moe"
reward_weighting: "likelihood"  # other options is "likelihood"
